remote_theme: "mmistakes/minimal-mistakes@4.26.2"

title: "Sudoku Solver"
description: "Sudoku Solver using Bitwise Operators in C"
baseurl: "/sudoku-solver" # Lascia vuoto se il sito è il repository principale
url: "https://antonioberna.github.io" # Modifica con il tuo URL GitHub Pages
author:
  name: "Antonio Bernardini"
  avatar: "/assets/imgs/me.jpg"

skin: "dark"

plugins:
  - jekyll-include-cache